spring:
  application:
    name: BOOKING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/eventspace?createDatabaseIfNotExist=true
    username: root
    password: Nikhil@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    IpAddress: 127.0.0.1

server:
  port: 8084
