spring:
   cloud:
     gateway:
       routes:
         - id : auth-service
           uri : lb://AUTH-SERVICE
           predicates :
             - Path=/auth/**
           filters:
             - CustomFilter
         - id: user-service
           uri: lb://USER-SERVICE
           predicates:
             - Path=/user/**
           filters:
             - CustomFilter
         - id: venue-service
           uri: lb://venue-service
           predicates:
             - Path=/venues/**
           filters:
             - CustomFilter
         - id: booking-service
           uri: lb://BOOKING-SERVICE
           predicates:
             - Path=/bookings/**
           filters:
             - CustomFilter

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 2
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    IpAddress: 127.0.0.1


