spring:
  application:
    name : EUREKA-SERVER

server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: MasamNikhil
    preferIpAddress: true
    IpAddress: 127.0.0.1